name:                gh-labels-hs
version:             0.1.0.0
github:              "jbristow/gh-labels-hs"
license:             BSD3
author:              "Jon Bristow"
maintainer:          "jonthegm@yahoo.com"
copyright:           "2018 Jon Bristow"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jbristow/gh-labels-hs#readme>

dependencies:
- base >= 4.10.1.0 && < 5
- text
- github
- cmdargs

library:
  source-dirs: src
  dependencies:
  - yaml
  - bytestring
  - aeson
  - vector

executables:
  gh-labels-hs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -Wall
    dependencies:
    - gh-labels-hs

tests:
  gh-labels-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -Wall
    dependencies:
    - gh-labels-hs
    - yaml
    - aeson
    - text
    - hspec
